version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - python3 -m venv ~/.containerized-flask-app && source ~/.containerized-flask-app/bin/activate
      - make install
      - sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 && sudo chmod +x /bin/hadolint
  build:
    commands:
      - source ~/.containerized-flask-app/bin/activate
      - make lint
      - make test