# main
name: Python 3.7.16
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.16
    - name: Install dependencies
      run: |
        make install
        
    - name: Install hadolint
      run: |
        bash install_hadolint.sh
        git update-index --chmod=+x /bin/hadolint

    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
